version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: whatssuite-dev-postgres
    environment:
      POSTGRES_DB: whatssuite_dev
      POSTGRES_USER: whatssuite_dev
      POSTGRES_PASSWORD: dev_password_123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./packages/db/prisma/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U whatssuite_dev -d whatssuite_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: whatssuite-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # API Service
  api:
    image: ghcr.io/${GITHUB_REPOSITORY:-whatssuite}:latest
    container_name: whatssuite-dev-api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://whatssuite_dev:dev_password_123@postgres:5432/whatssuite_dev?schema=public
      REDIS_URL: redis://redis:6379
      PORT: 3005
      JWT_SECRET: dev_jwt_secret_123
      WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN}
      WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}
      WHATSAPP_BUSINESS_ACCOUNT_ID: ${WHATSAPP_BUSINESS_ACCOUNT_ID}
      WEBHOOK_SECRET: dev_webhook_secret_123
    ports:
      - "3005:3005"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WhatsApp Service
  wapp-service:
    image: ghcr.io/${GITHUB_REPOSITORY:-whatssuite}:latest
    container_name: whatssuite-dev-wapp-service
    build:
      context: .
      dockerfile: Dockerfile
      target: wapp-service
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://whatssuite_dev:dev_password_123@postgres:5432/whatssuite_dev?schema=public
      REDIS_URL: redis://redis:6379
      PORT: 3007
      WHATSAPP_API_TOKEN: ${WHATSAPP_API_TOKEN}
      WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}
      WHATSAPP_BUSINESS_ACCOUNT_ID: ${WHATSAPP_BUSINESS_ACCOUNT_ID}
      QUEUE_CHANNEL: message-queue
      HEALTH_CHECK_INTERVAL: 30000
      GRACEFUL_SHUTDOWN_TIMEOUT: 10000
    ports:
      - "3007:3007"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Admin Dashboard
  admin:
    image: ghcr.io/${GITHUB_REPOSITORY:-whatssuite}:latest
    container_name: whatssuite-dev-admin
    build:
      context: .
      dockerfile: Dockerfile
      target: admin
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3005
      NEXT_PUBLIC_APP_URL: http://localhost:3006
      PORT: 3006
    ports:
      - "3006:3006"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Client
  web:
    image: ghcr.io/${GITHUB_REPOSITORY:-whatssuite}:latest
    container_name: whatssuite-dev-web
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3005
      NEXT_PUBLIC_APP_URL: http://localhost:3004
      PORT: 3004
    ports:
      - "3004:3004"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  default:
    name: whatssuite-dev-network
