version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile # Corrected: Points to the single root Dockerfile
      target: api # Added: Builds only the 'api' stage
    ports:
      - "3001:3001"
    env_file:
      - .env # Changed: Loads variables from the .env file
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  wapp-service:
    build:
      context: .
      dockerfile: Dockerfile # Corrected: Points to the single root Dockerfile
      target: wapp-service # Added: Builds only the 'wapp-service' stage
    env_file:
      - .env # Changed: Loads variables from the .env file
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile # Corrected: Points to the single root Dockerfile
      target: web # Added: Builds only the 'web' stage
    ports:
      - "3000:3000"
    env_file:
      - .env # Changed: Loads variables from the .env file
    depends_on:
      - api
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: Dockerfile # Corrected: Points to the single root Dockerfile
      target: admin # Added: Builds only the 'admin' stage
    ports:
      - "3002:3002"
    env_file:
      - .env # Changed: Loads variables from the .env file
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
