version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  wapp-service:
    build:
      context: .
      dockerfile: apps/wapp-service/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
