version: "3.8"

services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: whatssuite_postgres_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-whatssuite_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-whatssuite_dev}
    ports:
      - "5433:5432" # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-whatssuite_dev} -d ${POSTGRES_DB:-whatssuite_dev}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-dev:
    image: redis:7-alpine
    container_name: whatssuite_redis_dev
    ports:
      - "6380:6379" # Different port to avoid conflicts
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api
    container_name: whatssuite_api_dev
    ports:
      - "3005:3005" # Different port
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-whatssuite_dev}:${POSTGRES_PASSWORD:-dev_password}@postgres-dev:5432/${POSTGRES_DB:-whatssuite_dev}?schema=public
      REDIS_URL: redis://redis-dev:6379
      PORT: 3005
      PHONE_NUMBER_ID: ${PHONE_NUMBER_ID}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      WABA_ID: ${WABA_ID}
      WEBHOOK_VERIFY_TOKEN: ${WEBHOOK_VERIFY_TOKEN}
      META_API_VERSION: ${META_API_VERSION:-v21.0}
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages

  wapp-service-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: wapp-service
    container_name: whatssuite_wapp_dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${POSTGRES_USER:-whatssuite_dev}:${POSTGRES_PASSWORD:-dev_password}@postgres-dev:5432/${POSTGRES_DB:-whatssuite_dev}?schema=public
      REDIS_URL: redis://redis-dev:6379
      PHONE_NUMBER_ID: ${PHONE_NUMBER_ID}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      WABA_ID: ${WABA_ID}
      META_API_VERSION: ${META_API_VERSION:-v21.0}
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./apps/wapp-service:/app/apps/wapp-service
      - ./packages:/app/packages

  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: web
    container_name: whatssuite_web_dev
    ports:
      - "3004:3004" # Different port
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3005}
    depends_on:
      api-dev:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages

  admin-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: admin
    container_name: whatssuite_admin_dev
    ports:
      - "3003:3003" # Different port
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3005}
    depends_on:
      api-dev:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./apps/admin:/app/apps/admin
      - ./packages:/app/packages

volumes:
  postgres_dev_data:
