// buievo Type Definitions
// Export all type definitions from this package

// Database types
export * from './database';

// API types
export * from './api';

// WhatsApp types
export * from './whatsapp';

// Error handling types
export * from './errors';

// Configuration types
export * from './config';

// Event types
export * from './events';

// Utility types - export specific types to avoid conflicts
export type {
  Nullable,
  Optional,
  RequiredFields,
  OptionalFields,
  DeepPartial,
  DeepRequired,
  Mutable,
  Immutable,
  AsyncFunction,
  SyncFunction,
  FunctionWithContext,
  AsyncFunctionWithContext,
  PromiseResult,
  PromiseRejection,
  PromiseSettledResult,
  ArrayElement,
  NonEmptyArray,
  ArrayWithLength,
  ObjectKeys,
  ObjectValues,
  ObjectEntries,
  PickByValue,
  OmitByValue,
  StringLiteral,
  StringKeys,
  StringValues,
  NumberLiteral,
  PositiveNumber,
  NegativeNumber,
  NonZeroNumber,
  DateString,
  ISODateString,
  Timestamp,
  UUID,
  ID,
  AutoIncrementID,
  Email,
  PhoneNumber,
  URL,
  Status,
  ApprovalStatus,
  ProcessingStatus,
  PaginationParamsUtil,
  PaginationResult,
  SortOrder,
  SortDirection,
  SortParams,
  SortConfig,
  FilterOperator,
  FilterCondition,
  FilterParams,
  SearchParams,
  SearchResult,
  ValidationResultUtil,
  ValidationErrorUtil,
  ValidationWarningUtil,
  Success,
  Failure,
  Result,
  Some,
  None,
  Option,
  Left,
  Right,
  Either,
  CacheEntry,
  CacheConfigUtil,
  RetryConfig,
  RetryResult,
  QueueItem,
  QueueConfig,
  LogLevel,
  LogEntry,
  Logger,
  Metric,
  Counter,
  Gauge,
  Histogram,
  HealthCheck,
  HealthStatus,
  ConfigValue,
  ConfigChange,
  EventMetadata,
  ApiResponseWrapper,
  DatabaseConnection,
  QueryResult,
  FileInfo,
  FileUploadResult,
  TimeRange,
  TimeWindow,
  NetworkRequest,
  NetworkResponse,
  SecurityContext,
  Permission,
  Predicate,
  Mapper,
  Reducer,
  Comparator,
  Transformer,
  Validator
} from './utils';

// Middleware types - export specific types to avoid conflicts
export type {
  Request as MiddlewareRequest,
  Response as MiddlewareResponse,
  NextFunction as MiddlewareNextFunction,
  AuthenticatedRequest,
  ApiResponse,
  MiddlewareFunction,
  AuthMiddleware,
  AuthorizationMiddleware,
  ValidationMiddleware,
  RateLimitConfig,
  RateLimitMiddleware,
  LoggingMiddleware,
  CorsConfig,
  SecurityMiddleware,
  CacheConfig as MiddlewareCacheConfig,
  CacheMiddleware,
  ErrorHandlingMiddleware,
  RequestContext,
  ContextMiddleware,
  FileUploadConfig,
  FileUploadMiddleware,
  WebhookConfig as MiddlewareWebhookConfig,
  WebhookMiddleware,
  PerformanceConfig,
  PerformanceMiddleware,
  HealthCheckConfig as MiddlewareHealthCheckConfig,
  HealthCheckMiddleware,
  ApiDocsConfig,
  ApiDocsMiddleware,
  MiddlewareChain,
  MiddlewareFactory,
  MiddlewareContext,
  MiddlewareError,
  MiddlewareResult
} from './middleware';
